name: __dir__
type: signature
claimed-nist-level: __nist-level__
length-public-key: __length-public-key__
length-secret-key: __length-secret-key__
length-signature: __length-signature__
nistkat-sha256: __nistkat-sha256__
testvectors-sha256: __testvectors-sha256__
principal-submitters:
  - # TODO: add principal-submitters
auxiliary-submitters: # optional
  - # TODO: add auxiliary-submitters
implementations: # TODO: add optimized implementation
  - name: clean
    version: 1.2