name: __dir__
type: signature
claimed-nist-level: __nist-level__
length-public-key: __length-public-key__
length-secret-key: __length-secret-key__
length-signature: __length-signature__
nistkat-sha256: __nistkat-sha256__
testvectors-sha256: __testvectors-sha256__
principal-submitters:
  - Marco Baldi
  - Alessandro Barenghi
  - Sebastian Bitzer
  - Patrick Karl
  - Felice Manganiello
  - Alessio Pavoni
  - Gerardo Pelosi
  - Paolo Santini
  - Jonas Schupp
  - Freeman Slaughter
  - Antonia Wachter-Zeh
  - Violetta Weger
auxiliary-submitters:
  - TODO
implementations:
  - name: clean
    version: 1.2 + Keccak_x4 + PQClean fixes
  - name: avx2
    version: 1.2 + Keccak_x4 + PQClean fixes
    supported_platforms:
      - architecture: x86_64
        required_flags:
          - avx2