name: cross-rsdpg-128-balanced
type: signature
claimed-nist-level: 1
length-public-key: 54
length-secret-key: 32
length-signature: 9120
nistkat-sha256: 97be93b48229095f49d8a70eecd68903dd9c2088c0a723bc576751abf98e319e
testvectors-sha256: 94ce9dd921d4a74bff0f2e745e871fbb64a4aa0733685ad990d96053b5fbb2c7
principal-submitters:
  - Marco Baldi
  - Alessandro Barenghi
  - Michele Battagliola
  - Sebastian Bitzer
  - Patrick Karl
  - Felice Manganiello
  - Alessio Pavoni
  - Gerardo Pelosi
  - Paolo Santini
  - Jonas Schupp
  - Edoardo Signorini
  - Freeman Slaughter
  - Antonia Wachter-Zeh
  - Violetta Weger
auxiliary-submitters:
  - Marco Gianvecchio
implementations:
  - name: clean
    version: 2.0 + PQClean and OQS patches
  - name: avx2
    version: 2.0 + PQClean and OQS patches
    supported_platforms:
      - architecture: x86_64
        required_flags:
          - avx2