name: cross-rsdpg-256-small
type: signature
claimed-nist-level: 5
length-public-key: 106
length-secret-key: 64
length-signature: 36454
nistkat-sha256: f4fc8719a1bf18bc016ea7b2d172110cf82bc464d595014d9f4a72b6eb196470
testvectors-sha256: 3707eb6a8582d4188adbbd1c7f97a08ea46425d7425357a090225490bca9faaa
principal-submitters:
  - Marco Baldi
  - Alessandro Barenghi
  - Michele Battagliola
  - Sebastian Bitzer
  - Patrick Karl
  - Felice Manganiello
  - Alessio Pavoni
  - Gerardo Pelosi
  - Paolo Santini
  - Jonas Schupp
  - Edoardo Signorini
  - Freeman Slaughter
  - Antonia Wachter-Zeh
  - Violetta Weger
auxiliary-submitters:
  - Marco Gianvecchio
implementations:
  - name: clean
    version: 2.0 + PQClean and OQS patches
  - name: avx2
    version: 2.0 + PQClean and OQS patches
    supported_platforms:
      - architecture: x86_64
        required_flags:
          - avx2