name: cross-rsdpg-256-fast
type: signature
claimed-nist-level: 5
length-public-key: 106
length-secret-key: 64
length-signature: 48102
nistkat-sha256: ce480adf4d0afa394edc7fb319217c980bef7d6d8425890c165b7971619aa6f5
testvectors-sha256: c7c2d9794c099196907ec9d1ac1c5e9156a15ef71c67e98039b000dd8ea1c68f
principal-submitters:
  - Marco Baldi
  - Alessandro Barenghi
  - Michele Battagliola
  - Sebastian Bitzer
  - Patrick Karl
  - Felice Manganiello
  - Alessio Pavoni
  - Gerardo Pelosi
  - Paolo Santini
  - Jonas Schupp
  - Edoardo Signorini
  - Freeman Slaughter
  - Antonia Wachter-Zeh
  - Violetta Weger
auxiliary-submitters:
  - Marco Gianvecchio
implementations:
  - name: clean
    version: 2.0 + PQClean and OQS patches
  - name: avx2
    version: 2.0 + PQClean and OQS patches
    supported_platforms:
      - architecture: x86_64
        required_flags:
          - avx2