name: cross-rsdp-128-small
type: signature
claimed-nist-level: 1
length-public-key: 77
length-secret-key: 32
length-signature: 10080
nistkat-sha256: ert
testvectors-sha256: ert
principal-submitters: #TODO: check submitters
  - Marco Baldi
  - Alessandro Barenghi
  - Sebastian Bitzer
  - Patrick Karl
  - Felice Manganiello
  - Alessio Pavoni
  - Gerardo Pelosi
  - Paolo Santini
  - Jonas Schupp
  - Freeman Slaughter
  - Antonia Wachter-Zeh
  - Violetta Weger
implementations:
  - name: clean
    version: 1.2
  - name: avx2
    version: 1.2
    supported_platforms:
      - architecture: x86_64
        required_flags:
          - avx2